version: "3.8"

services:
  vod:
    # 以前是 image: sifan1/vodspider:latest
    # 现在改成 build: . 
    # 意思是用当前目录下的 Dockerfile 构建
    build: .
    container_name: vod
    restart: always
    ports:
      - 8080:3000
    environment:
      # 即使这里写了，Zeabur 环境变量里也要填
      REDIS_HOST: placeholder
      REDIS_PORT: 6379
